title: Chen Tao (Jennifer)
logo: /assets/img/logo.png
position: Research Engineer at A*STAR
# description: Never be so polite, you forget your power; Never wield such power, you forget to be polite.
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: light
favicon: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
# Icons available via https://fontawesome.com/search?q=linkedin&o=r
sidebar:
  - name: Google Scholar
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
    link: https://scholar.google.com/citations?user=cB13SBUAAAAJ&hl=en
  - name: Email
    icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:taoc@i2r.a-star.edu.sg
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/TAOC0002 
  - name: Linkedin
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/chen-tao-16a91b201/
  - name: CV
    icon: <i class="fa-solid fa-file"></i>
    link: ./files/CV.pdf
  # - name: Blog
  #   icon: <i class="fa-solid fa-pen"></i>
  #   link: https://www.bodunhu.com/blog/
  # - name: Project Repository
  #   icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/></g></svg>
  #   link: https://github.com/BDHU/minimalist

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
